=== sinem/WBA2-PHASE2-PRMF/Meilenstein 1 - XML Schema/Profile.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/Profil" xmlns:tns="http://www.example.org/Profil" elementFormDefault="qualified">
	<xs:element name="UserProfile">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="UserID" type="xs:int" />
				<xs:element name="UserName" type="xs:string" />
				<xs:element name="UserInformation">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="FirstName" type="xs:string" />
							<xs:element name="LastName" type="xs:string" />
							<xs:element name="Age" type="xs:int" />
							<xs:element name="City" type="xs:string" />
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="Subscriptions" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="ChannelName" />
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== sinem/WBA2-PHASE2-PRMF/Meilenstein 2 - Ressourcen und Semantik der HTTP-Operationen/Ressourcen/Profile.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:UserProfile xmlns:tns="http://www.example.org/Profil" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/Profil Profile.xsd ">
  <tns:UserID>0</tns:UserID>
  <tns:UserName>tns:UserName</tns:UserName>
  <tns:UserInformation>
    <tns:FirstName>tns:FirstName</tns:FirstName>
    <tns:LastName>tns:LastName</tns:LastName>
    <tns:Age>0</tns:Age>
    <tns:City>tns:City</tns:City>
  </tns:UserInformation>
  <tns:Subscriptions>
    <tns:ChannelName/>
  </tns:Subscriptions>
</tns:UserProfile>
